public class assignmentAccountHelper {
     public static void billingAddress(List <account>acc){ 
        assignmentAccountHandler.billingAddress(acc);
    }
    Public static void updateOppty(Map<id,account>acc){
        assignmentAccountHandler.updateOppty(acc);
    }
    Public static void sendMail(List<account>acc){
        assignmentAccountHandler.sendMail(acc);
    }Public static void totalOppty(List<account>acc){
        assignmentAccountHandler.totalOppty(acc);
    }Public static void duplicateRecord(List<account>acc){
        assignmentAccountHandler.duplicateRecord(acc);
    }

}